#include "../includes/zimm/detail/utils.hpp"
#include "../includes/zimm/zimm.hpp"
#include <cstdlib>
#include <filesystem>
#include <format>
#include <fstream>
#include <iostream>
#include <set>
#include <string>

namespace fs = std::filesystem;

namespace zimm
{

std::string_view get_assumed_path(const Target &target)
{
    for (auto &pobj : target.private_properties())
        if (pobj->type() == PropertyType::AssumedProperty)
            return static_cast<const AssumedProperty &>(*pobj).path();
    return "";
};

std::string ninja_target_name(const Target &target)
{
    switch (target.type())
    {
    case TargetType::Executable:
        return std::string{target.name()};
    case TargetType::StaticLibrary:
        return std::format("{}.a", target.name());
    case TargetType::SharedLibrary:
        return std::format("lib{}.so", target.name());
    case TargetType::ThirdPartyTarget:
        return std::format("{}_tpt", target.name());
    case TargetType::CustomTarget:
        return std::format("{}_ct", target.name());
    }
    return "Unknown";
}

std::string get_compile_flags(std::span<const PropertyObject> props)
{
    std::ostringstream oss;
    for (const auto &prop : props)
    {
        if (prop->type() == PropertyType::Include)
            oss << "-I" << static_cast<const IncludeProperty &>(*prop).include_path() << " ";
        else if (prop->type() == PropertyType::CompileFlag)
            oss << static_cast<const CompileFlagProperty &>(*prop).flag() << " ";
    }
    return std::move(oss).str();
}

std::string get_link_flags(std::span<const PropertyObject> props)
{
    std::ostringstream oss;
    for (const auto &prop : props)
    {
        if (prop->type() == PropertyType::LinkFlag)
            oss << static_cast<const LinkFlagProperty &>(*prop).flag();
    }
    return std::move(oss).str();
}

std::string get_deps_list(const Target &target)
{
    std::ostringstream oss;
    for (const auto *dep : target.dependencies()) oss << ninja_target_name(*dep) << ' ';
    return std::move(oss.str());
}

std::string get_link_sources(std::span<const PropertyObject> props)
{
    std::ostringstream oss;
    for (const auto &prop : props)
    {
        if (prop->type() != PropertyType::LinkTarget) continue;
        oss << ninja_target_name(*static_cast<const LinkTargetProperty &>(*prop).link_lib()) << " ";
    }
    return std::move(oss).str();
}

std::string ninja_target_name(std::string_view fileAbsPath /* cxx or c file */)
{
    std::string objectFilePath{fileAbsPath};
    objectFilePath += ".o";
    for (auto &c : objectFilePath)
        if (c == '/') c = '_';
    return objectFilePath;
}

void generate_build(Project &project)
{
    project.fold_post_order(
        [&](Target *tRef)
        {
            Target &t = *tRef;
            for (auto dep : t.dependencies())
                for (auto p : dep->public_properties()) t.add_property(public_, p);
        });

    project.fold_post_order(
        [&](const Target *t)
        {
            if (t->type() != TargetType::ThirdPartyTarget) return;
            auto &tpt = static_cast<const ThirdPartyTarget &>(*t);
            auto metaCmd = tpt.meta_build_cmd();
            if (metaCmd.empty()) return;

            std::string metaStamp = std::format("{}.meta.stamp", t->name());
            if (fs::exists(metaStamp)) return;

            fs::create_directories(fs::path{tpt.build_dir()});
            std::string cmd =
                std::format("cd {} && {} && touch {}", tpt.build_dir(), metaCmd, metaStamp);
            if (std::system(cmd.c_str()) != 0)
                LOGF("Warning: meta-build step for '" << tpt.name() << "' failed (continuing)\n");
        });

    std::string ninja = "build.ninja";
    std::ofstream out(ninja);
    if (!out) LOGF("Error: could not open " << ninja << " for writing");

    out << "# Generated by zimm — do not edit by hand\n";
    out << "ninja_required_version = 1.10\n\n";

    const auto &config = project.config();

    std::string gxx = config.toolchain_prefix + "g++";
    std::string gcc = config.toolchain_prefix + "gcc";
    std::string ar = config.toolchain_prefix + "ar";
    std::string ld = config.toolchain_prefix + "g++";

    out << "rule cxx\n";
    out << "  command = " << gxx << " -MD -MT $out -MF $out.d -c $in -o $out $flags\n";
    out << "  depfile = $out.d\n";
    out << "  deps = gcc\n";
    out << "  description = CXX $out\n\n";

    out << "rule cc\n";
    out << "  command = " << gcc << " -MD -MT $out -MF $out.d -c $in -o $out $flags\n";
    out << "  depfile = $out.d\n";
    out << "  deps = gcc\n";
    out << "  description = CC $out\n\n";

    out << "rule ar\n";
    out << "  command = " << ar << " rcs $out $in\n";
    out << "  description = AR $out\n\n";

    out << "rule link\n";
    out << "  command = " << ld << " $in -o $out $ldflags\n";
    out << "  description = LINK $out\n\n";

    out << "rule run_cmd\n";
    out << "  command = (cd $dir && $cmd) && touch $out\n";
    out << "  description = $desc\n\n";

    out << "rule assumed_target\n";
    out << "  command = true\n";
    out << "  description = assumed target stub\n\n";

    std::string globalCompileFlags = get_compile_flags(project.global_properties());
    std::string globalLinkFlags = get_link_flags(project.global_properties());

    project.fold_post_order(
        [&](const Target *targetPtr) -> void
        {
            const Target &target = *targetPtr;
            auto assumedPath = get_assumed_path(target);
            auto depList = get_deps_list(target);
            auto ninjaName = ninja_target_name(target);

            std::string localCompileFlags = get_compile_flags(target.public_properties()) + " " +
                                            get_compile_flags(target.private_properties());

            std::string localLinkFlags = get_link_flags(target.public_properties()) + " " +
                                         get_link_flags(target.private_properties());

            // is an assumed target
            if (!assumedPath.empty())
            {
                out << "build " << assumedPath << ": assumed_target\n\n";
                return;
            }

            std::string sourceObjectsNinjaNames;
            bool depsEnsured = false;
            if (auto sourcesPtr = dynamic_cast<const detail::Sources *>(targetPtr))
            {
                std::vector<std::string> objectNinjaNames;
                for (std::string_view src : sourcesPtr->sources())
                {
                    depsEnsured = true;
                    bool isCxx = utils::is_cxx_source(src);
                    std::string_view rule = isCxx ? "cxx" : "cc";
                    std::string objectNinjaName = ninja_target_name(src);
                    out << "build " << objectNinjaName << ": " << rule << " " << src << " | "
                        << depList << '\n';
                    sourceObjectsNinjaNames += " " + objectNinjaName;

                    out << "  flags = " << globalCompileFlags;
                    out << " " << localCompileFlags;
                    out << " " << (isCxx ? config.cxx_flags : config.c_flags);
                    out << "\n\n";
                }
            }

            std::string linkSourcesNinjaNames = get_link_sources(target.public_properties()) +
                                                get_link_sources(target.private_properties());

            switch (target.type())
            {
            case TargetType::StaticLibrary:
            {
                auto &lib = static_cast<const StaticLibrary &>(target);
                out << "build " << ninja_target_name(lib) << ": ar " << sourceObjectsNinjaNames
                    << " " << linkSourcesNinjaNames;
                if (!depsEnsured) out << " | " << depList;
                out << "\n\n";
                break;
            }
            case TargetType::SharedLibrary:
            {
                auto &lib = static_cast<const SharedLibrary &>(target);
                out << "build " << ninja_target_name(lib) << ": link " << sourceObjectsNinjaNames
                    << " " << linkSourcesNinjaNames;
                if (!depsEnsured) out << " | " << depList;
                out << '\n';
                out << "  ldflags = -shared " << globalLinkFlags << " " << localLinkFlags << "\n\n";
                break;
            }
            case TargetType::Executable:
            {
                auto &exec = static_cast<const Executable &>(target);
                out << "build " << ninja_target_name(exec) << ": link " << sourceObjectsNinjaNames
                    << " " << linkSourcesNinjaNames;
                if (!depsEnsured) out << " | " << depList;
                out << '\n';
                out << "  ldflags = " << globalLinkFlags << " " << localLinkFlags << "\n\n";
                break;
            }
            case TargetType::ThirdPartyTarget:
            {
                auto &tpt = static_cast<const ThirdPartyTarget &>(target);
                auto build = tpt.build_cmd();
                if (build.empty()) build = "true";

                // Third Party Target is not expected to have sources
                if (depsEnsured) LOGF("Why does Third Party Target have sources?");
                out << "build " << ninja_target_name(tpt) << ": run_cmd | " << depList << "\n";

                // Directory already created before executing meta command
                out << "  dir = " << tpt.build_dir() << "\n";
                out << "  cmd = " << build << "\n";
                out << "  desc = BUILD " << tpt.name() << "\n\n";
                break;
            }
            case TargetType::CustomTarget:
            {
                auto &ct = dynamic_cast<const detail::CustomTargetBase &>(target);
                fs::create_directories(fs::path{ct.dir().path()});

                out << "build";
                for (auto &o : ct.outputs()) out << " " << o;
                out << " " << ninja_target_name(target);
                out << ": run_cmd";
                for (auto &i : ct.inputs()) out << " " << i;
                out << " | " << depList << "\n";

                // Third Party Target is not expected to have sources
                if (depsEnsured) LOGF("Why does Third Party Target have sources?");

                out << "  dir = " << ct.dir().path() << "\n";
                out << "  cmd = " << ct.generate_cmd() << "\n";
                out << "  desc = CUSTOM " << target.name() << "\n\n";
                break;
            }
            }
        });

    // --- Install rules ---
    const auto &install_map = project.installer()->map();
    if (!install_map.empty())
    {
        std::string install_dir = config.install_dir;

        out << "\n# --- Install rules ---\n\n";
        out << "rule install_file\n";
        out << "  command = install -D $in $out\n";
        out << "  description = INSTALL $out\n\n";

        out << "rule install_tree\n";
        out << "  command = mkdir -p $dest && cp -r $dir/. $dest/\n";
        out << "  description = INSTALL $dir -> $dest\n\n";

        // Emit per-file install edges first, collecting phony targets.
        std::vector<std::string> phony_targets;

        for (auto &[rel_dest, sources] : install_map)
        {
            for (size_t i = 0; i < sources.size(); ++i)
            {
                auto &src = sources[i];
                if (src.back() == '/')
                {
                    // directory source → tree copy
                    std::string target = "install_" + rel_dest + "_" + std::to_string(i);
                    phony_targets.push_back(target);
                    out << "build " << target << ": install_tree\n";
                    out << "  dir = " << src << "\n";
                    out << "  dest = " << (fs::path(install_dir) / rel_dest).string() << "\n";
                }
                else
                {
                    // file source → single copy
                    std::string filename = fs::path(src).filename().string();
                    std::string dest = (fs::path(install_dir) / rel_dest / filename).string();
                    phony_targets.push_back(dest);
                    out << "build " << dest << ": install_file " << filename << "\n";
                }
            }
        }

        // Emit the `install` phony target pointing at everything above.
        out << "build install: phony";
        for (auto &t : phony_targets) out << " " << t;
        out << "\n\n";
    }

    out.close();
    std::cout << "Done. Run `ninja` to build.\n";
}

//  Feature detection
bool Project::try_compile(std::string source, bool link)
{
    namespace fs = fs;
    auto work_dir = fs::path{m_featureDetectionDir.path()};

    std::set<std::string> includes;
    std::set<std::string> compile_flags;
    std::set<std::string> link_flags;

    for (auto &pobj : m_globalProperties)
    {
        const Property &prop = *pobj;
        switch (prop.type())
        {
        case PropertyType::Include:
            includes.insert(std::string{static_cast<const IncludeProperty &>(prop).include_path()});
            break;
        case PropertyType::CompileFlag:
            compile_flags.insert(
                std::string{static_cast<const CompileFlagProperty &>(prop).flag()});
            break;
        case PropertyType::LinkFlag:
            link_flags.insert(std::string{static_cast<const LinkFlagProperty &>(prop).flag()});
            break;
        default:
            break;
        }
    }

    std::string cxxflags = m_config.cxx_flags;
    for (auto &inc : includes) cxxflags += " -I" + inc;
    for (auto &f : compile_flags) cxxflags += " " + f;

    // --- write source file ---

    constexpr auto name = "zimm_check";
    auto src_path = work_dir / std::format("{}.cpp", name);
    {
        std::ofstream src_file(src_path);
        if (!src_file) return false;
        src_file << source;
    }

    // --- compile ---

    auto obj_path = work_dir / std::format("{}.o", name);
    auto err_path = work_dir / std::format("{}.err", name);

    std::string compiler = m_config.toolchain_prefix + "g++";

    auto compile_cmd = std::format("{} {} -c {} -o {} 2>{}", compiler, cxxflags, src_path.string(),
                                   obj_path.string(), err_path.string());

    if (std::system(compile_cmd.c_str()) != 0) return false;

    if (link)
    {
        std::string ldflags;
        for (auto &f : link_flags) ldflags += " " + f;

        auto bin_path = work_dir / name;
        auto link_cmd = std::format("{} {} {} -o {} 2>>{}", compiler, obj_path.string(), ldflags,
                                    bin_path.string(), err_path.string());

        if (std::system(link_cmd.c_str()) != 0) return false;
    }

    return true;
}

std::optional<std::string> Project::try_run(std::string source)
{
    namespace fs = fs;

    if (!try_compile(std::move(source), /*link=*/true)) return std::nullopt;

    auto work_dir = fs::path{m_featureDetectionDir.path()};
    constexpr auto name = "zimm_check";

    auto bin_path = work_dir / name;
    auto out_path = work_dir / std::format("{}.out", name);
    auto err_path = work_dir / std::format("{}.err", name);

    auto run_cmd =
        std::format("{} > {} 2>>{}", bin_path.string(), out_path.string(), err_path.string());

    if (std::system(run_cmd.c_str()) != 0) return std::nullopt;

    std::ifstream out_file(out_path);
    if (!out_file) return std::nullopt;

    std::string result(std::istreambuf_iterator<char>{out_file}, std::istreambuf_iterator<char>{});
    return result;
}

bool Project::check_header(std::string header)
{
    auto src = std::format("#include <{0}>\n"
                           "int main() {{ return 0; }}\n",
                           header);
    return try_compile(std::move(src), /*link=*/false);
}

bool Project::check_function_exists(std::string function_name)
{
    auto src = std::format("#ifdef __cplusplus\n"
                           "extern \"C\" {{\n"
                           "#endif\n"
                           "char {0}();\n"
                           "#ifdef __cplusplus\n"
                           "}}\n"
                           "#endif\n"
                           "int main() {{ (void){0}(); return 0; }}\n",
                           function_name);
    return try_compile(std::move(src), /*link=*/true);
}

bool Project::check_symbol_exists(std::string symbol, std::vector<std::string> headers)
{
    std::string header_block;
    for (const auto &h : headers) header_block += std::format("#include <{}>\n", h);

    auto src = std::format("{}"
                           "int main() {{\n"
                           "    (void)({});\n"
                           "    return 0;\n"
                           "}}\n",
                           header_block, symbol);
    return try_compile(std::move(src), /*link=*/false);
}

std::optional<size_t> Project::check_type_size(std::string type, std::vector<std::string> headers)
{
    std::string header_block;
    for (const auto &h : headers) header_block += std::format("#include <{}>\n", h);

    auto src = std::format("{}"
                           "#include <cstdio>\n"
                           "int main() {{\n"
                           "    std::printf(\"%zu\\n\", sizeof({}));\n"
                           "    return 0;\n"
                           "}}\n",
                           header_block, type);

    auto output = try_run(std::move(src));
    if (!output) return std::nullopt;

    return std::stoull(*output);
}

} // namespace zimm
